/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_BULLETPROOFS-TEST__
#define __RUST_BULLETPROOFS-TEST__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct {

    uint64_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint64_t;

typedef struct { uint8_t idx[32]; } uint8_32_array_t;

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct {

    uint8_32_array_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint8_32_array_t;

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct {

    uint8_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint8_t;

Vec_uint8_t bulletproofs_prove_multiple (
    Vec_uint64_t const * witness,
    Vec_uint8_32_array_t const * blindings);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_BULLETPROOFS-TEST__ */
