// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs /Users/Macbook_Autonomous/work/go/src/github.com/dat-incognito-org/newbp/bulletproofs/exports.go

package bulletproofs

type c_bytes32 struct {
        Idx [32]uint8
}
type c_bytes32_slice struct {
        Ptr     *c_bytes32
        Len     uint64
        Cap     uint64
}
type c_uint64_slice struct {
        Ptr     *uint64
        Len     uint64
        Cap     uint64
}